version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_review
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg2://postgres:postgres@db:5432/ai_review}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      API_PORT: ${API_PORT:-8000}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    environment:
      VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8000}
      VITE_FEATURE_FLAGS: ${VITE_FEATURE_FLAGS:-demo,checks_api,sarif}
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

volumes:
  db_data: