apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-code-review-squad.fullname" . }}-backend
  labels: {{ include "ai-code-review-squad.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ai-code-review-squad.name" . }}
    app.kubernetes.io/component: backend