apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-code-review-squad.fullname" . }}-frontend
  labels: {{ include "ai-code-review-squad.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ai-code-review-squad.name" . }}
    app.kubernetes.io/component: frontend