apiVersion: v2
name: ai-code-review-squad
description: Helm chart for deploying the ai‑code‑review‑squad application
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: postgresql
    version: "12.1.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.10.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled